$(function(){
  
  var exampleApps = [
    {"info":{"author":"automata","title":"meemoo intro","description":"Meemoo introduction","parents":["https://gist.github.com/3282702","https://gist.github.com/5110822"],"url":"intro"},"nodes":[{"src":"http://automata.github.com/meemoo-intro/introduction.html","x":187,"y":65,"z":0,"w":405,"h":329,"state":{},"id":0},{"src":"http://automata.github.com/meemoo-intro/switch.html","x":82,"y":466,"z":0,"w":200,"h":210,"state":{},"id":1},{"src":"http://automata.github.com/meemoo-intro/lamp.html","x":484,"y":462,"z":0,"w":469,"h":238,"state":{},"id":2}],"edges":[]},
    {"info":{"title":"cam to gif","author":"forresto","description":"webcam to animated gif","url":"cam2gif"},"nodes":[{"id":1,"src":"meemoo:ui/button","x":133,"y":111,"w":242,"h":61,"state":{"label":"add frame"}},{"id":2,"src":"meemoo:image/cam","x":126,"y":247,"w":309,"h":389,"state":{"width":300,"height":300,"fps":20}},{"id":3,"src":"meemoo:variable/animation","x":615,"y":80,"w":341,"h":559,"state":{"fps":12,"pingpong":true}}],"edges":[{"source":[1,"bang"],"target":[2,"send"]},{"source":[2,"image"],"target":[3,"push"]}]},
    {"info":{"title":"cam to macro","author":"forresto","description":"webcam plus two titles","url":"macro"},"nodes":[{"id":7,"src":"meemoo:image/cam","x":119,"y":65,"w":261,"h":332,"state":{"width":300,"height":300,"fps":20}},{"id":8,"src":"meemoo:image/text","x":124,"y":453,"w":274,"h":96,"state":{"text":"top text","font":"bold 30px Tahoma","height":60,"fill":"white","stroke":"black","strokewidth":1.5}},{"id":9,"src":"meemoo:image/text","x":114,"y":611,"w":298,"h":111,"state":{"text":"bottom text","font":"bold 40px Tahoma","height":80,"fill":"white","stroke":"black","strokewidth":2}},{"id":10,"src":"meemoo:image/layers","x":626,"y":134,"w":441,"h":350,"state":{"layers":[{"name":"canvas-7","visible":true,"sort":1,"x":0,"y":0},{"name":"canvas-9","visible":true,"sort":2,"x":26,"y":250},{"name":"canvas-8","visible":true,"sort":3,"x":76,"y":3}],"width":300,"height":300}},{"id":5,"src":"meemoo:variable/animation","x":707,"y":675,"w":355,"h":558,"state":{"fps":12,"pingpong":false}}],"edges":[{"source":[8,"image"],"target":[10,"image"]},{"source":[9,"image"],"target":[10,"image"]},{"source":[7,"stream"],"target":[10,"image"]},{"source":[10,"image"],"target":[5,"push"]}]},
    {"info":{"title":"cam to glitch","author":"forresto","description":"webcam to jpg to glitch","url":"glitch"},"nodes":[{"src":"http://forresto.github.com/meemoo-modules/metronome.html","x":139,"y":45,"w":200,"h":100,"state":{"bpm":150},"id":1},{"src":"http://forresto.github.com/meemoo-camcanvas/webcam2jpg.html","x":581,"y":49,"w":339,"h":283,"state":{"quality":20,"width":320,"height":240},"id":2},{"src":"http://forresto.github.com/meemoo-jpgglitch/jpgglitch.html","x":138,"y":220,"w":339,"h":262,"state":{},"id":4},{"src":"http://forresto.github.com/meemoo-modules/img2canvas.html","x":282,"y":559,"w":116,"h":98,"state":{},"id":5},{"src":"http://forresto.github.com/meemoo-modules/reflow.html","x":646,"y":398,"w":256,"h":297,"state":{},"id":3}],"edges":[{"source":[1,"beat"],"target":[2,"capture"]},{"source":[2,"jpg"],"target":[4,"jpg"]},{"source":[5,"image"],"target":[3,"image"]},{"source":[4,"jpg"],"target":[5,"dataurl"]}]},
    {"info":{"title":"doodle flipbook","author":"forresto","description":"paint doodle to image array to animated gif","url":"flipbook"},"nodes":[{"src":"http://forresto.github.com/meemoo-paint/paint.html","x":132,"y":45,"w":377,"h":342,"state":{},"id":1},{"src":"http://forresto.github.com/meemoo-modules/canvasarray.html","x":760,"y":401,"w":348,"h":290,"state":{},"id":3},{"src":"http://forresto.github.com/meemoo-canvas2gif/canvas2gif.html","x":702,"y":43,"w":354,"h":291,"state":{"delay":200,"quality":75,"matte":"#FFFFFF"},"id":2},{"src":"http://forresto.github.com/meemoo-modules/imgur.html","x":1275,"y":81,"w":357,"h":297,"state":{"title":"meemoo/flipbook image share","caption":"This image was created with a Meemoo composition. http://meemoo.org/iframework/#/example/flipbook"},"id":6}],"edges":[{"source":[1,"image"],"target":[1,"tracing"]},{"source":[1,"image"],"target":[2,"image"]},{"source":[1,"image"],"target":[3,"image"]},{"source":[3,"image"],"target":[2,"image"]},{"source":[2,"gif"],"target":[6,"dataurl"]}]},
    {"info":{"title":"cam doodle","author":"forresto","description":"webcam to processing doodle to animated gif","url":"camdoodle"},"nodes":[{"src":"http://forresto.github.com/meemoo-camcanvas/onionskin.html","x":126,"y":43,"w":342,"h":283,"state":{"quality":75,"width":320,"height":240},"id":4},{"src":"http://forresto.github.com/meemoo-paint/paint.html","x":634,"y":53,"w":377,"h":342,"state":{},"id":1},{"src":"http://forresto.github.com/meemoo-canvas2gif/canvas2gif.html","x":125,"y":386,"w":354,"h":341,"state":{"delay":200,"quality":75,"matte":"#FFFFFF"},"id":2},{"src":"http://forresto.github.com/meemoo-modules/imgur.html","x":652,"y":456,"w":357,"h":297,"state":{"title":"meemoo/camdoodle image share","caption":"This image was created with a Meemoo composition. http://meemoo.org/iframework/#/example/camdoodle"},"id":6}],"edges":[{"source":[4,"image"],"target":[1,"image"]},{"source":[1,"image"],"target":[2,"image"]},{"source":[2,"gif"],"target":[6,"dataurl"]}]},
    {"info":{"title":"(speech to) text to speech","author":"forresto","description":"(in chrome, speech to) text to speech","url":"text2speech"},"nodes":[{"src":"http://forresto.github.com/meemoo-modules/speech2text.html","x":162,"y":61,"w":346,"h":98,"state":{},"id":1},{"src":"http://forresto.github.com/meemoo-speak.js/text2speech.html","x":234,"y":221,"w":167,"h":117,"state":{"amplitude":100,"pitch":50,"speed":175,"wordgap":0},"id":2},{"src":"http://forresto.github.com/meemoo-modules/audioarray.html","x":657,"y":227,"w":330,"h":280,"state":{},"id":3}],"edges":[{"source":[2,"info"],"target":[3,"title"]},{"source":[2,"audio"],"target":[3,"audio"]},{"source":[1,"text"],"target":[2,"text"]}]}
  ];

  Iframework.loadExampleApps(exampleApps);

});
