$(function () {
  // prettier-ignore
  var exampleApps = [
    {"info":{"author":"automata","title":"meemoo intro","description":"Meemoo introduction, made by @aut0mata in 2012 with iframe modules and Mozilla's Popcorn.js","parents":["https://gist.github.com/3282702","https://gist.github.com/5110822"],"url":"intro"},"nodes":[{"src":"https://forresto.github.io/meemoo-intro/introduction.html","x":187,"y":65,"z":0,"w":405,"h":329,"state":{},"id":0},{"src":"https://forresto.github.io/meemoo-intro/switch.html","x":82,"y":466,"z":0,"w":200,"h":210,"state":{},"id":1},{"src":"https://forresto.github.io/meemoo-intro/lamp.html","x":484,"y":462,"z":0,"w":469,"h":238,"state":{},"id":2}],"edges":[]},
    {"info":{"title":"cam to gif","author":"forresto","description":"webcam to animated gif","url":"cam2gif"},"nodes":[{"id":1,"src":"meemoo:ui/button","x":133,"y":111,"w":242,"h":61,"state":{"label":"add frame"}},{"id":2,"src":"meemoo:image/cam","x":126,"y":247,"w":309,"h":389,"state":{"width":500,"height":500,"fps":12,"showOnionskin":true}},{"id":3,"src":"meemoo:variable/animation","x":615,"y":80,"w":341,"h":559,"state":{"fps":6,"pingpong":false}}],"edges":[{"source":[1,"bang"],"target":[2,"send"]},{"source":[2,"image"],"target":[3,"push"]}]},
    {"info":{"title":"cam to gif station","author":"forresto","description":"webcam to animated gif","url":"kiosk","parents":["https://gist.github.com/ea32c33a741119e82c35"]},"nodes":[{"id":1,"src":"meemoo:ui/button","x":113,"y":70,"w":450,"h":212,"state":{"label":"add frame","background":"rgb(197, 255, 197)","key":"a"}},{"id":2,"src":"meemoo:image/cam","x":869,"y":219,"w":309,"h":389,"state":{"width":300,"height":300,"fps":20,"start":true}},{"id":3,"src":"meemoo:variable/animation","x":1472,"y":69,"w":367,"h":1053,"state":{"fps":6,"play":true}},{"id":4,"src":"meemoo:ui/button","x":171,"y":508,"w":212,"h":90,"state":{"label":"start over","color":"white","background":"red","key":"x"}},{"id":5,"src":"meemoo:ui/checkbox","x":592,"y":399,"w":80,"h":68,"state":{"value":true}},{"id":6,"src":"meemoo:ui/button","x":877,"y":62,"w":209,"h":77,"state":{"label":"start camera"}}],"edges":[{"source":[1,"bang"],"target":[2,"send"]},{"source":[2,"image"],"target":[3,"push"]},{"source":[4,"bang"],"target":[5,"off"]},{"source":[5,"checked"],"target":[2,"showOnionskin"]},{"source":[1,"bang"],"target":[5,"on"]},{"source":[4,"bang"],"target":[3,"clear"]},{"source":[6,"bang"],"target":[2,"start"]}]},
    {"info":{"title":"cam to macro","author":"forresto","description":"webcam plus two titles","url":"macro"},"nodes":[{"id":7,"src":"meemoo:image/cam","x":119,"y":65,"w":261,"h":332,"state":{"width":300,"height":300,"fps":20}},{"id":8,"src":"meemoo:image/text","x":124,"y":453,"w":274,"h":96,"state":{"text":"top text","font":"bold 30px Tahoma","height":60,"fill":"white","stroke":"black","strokewidth":1.5}},{"id":9,"src":"meemoo:image/text","x":114,"y":611,"w":298,"h":111,"state":{"text":"bottom text","font":"bold 40px Tahoma","height":80,"fill":"white","stroke":"black","strokewidth":2}},{"id":10,"src":"meemoo:image/layers","x":626,"y":134,"w":441,"h":350,"state":{"layers":[{"name":"canvas-7","visible":true,"sort":1,"x":0,"y":0},{"name":"canvas-9","visible":true,"sort":2,"x":26,"y":250},{"name":"canvas-8","visible":true,"sort":3,"x":76,"y":3}],"width":300,"height":300,"tile":false}}],"edges":[{"source":[8,"image"],"target":[10,"image"]},{"source":[9,"image"],"target":[10,"image"]},{"source":[7,"stream"],"target":[10,"image"]}]},
    // {"info":{"title":"cam to glitch","author":"forresto","description":"webcam to jpg to glitch","url":"glitch"},"nodes":[{"src":"https://forresto.github.io/meemoo-modules/metronome.html","x":139,"y":45,"w":200,"h":100,"state":{"bpm":150},"id":1},{"src":"https://forresto.github.io/meemoo-camcanvas/webcam2jpg.html","x":581,"y":49,"w":339,"h":283,"state":{"quality":20,"width":320,"height":240},"id":2},{"src":"https://forresto.github.io/meemoo-jpgglitch/jpgglitch.html","x":138,"y":220,"w":339,"h":262,"state":{},"id":4},{"src":"https://forresto.github.io/meemoo-modules/img2canvas.html","x":282,"y":559,"w":116,"h":98,"state":{},"id":5},{"src":"https://forresto.github.io/meemoo-modules/reflow.html","x":646,"y":398,"w":256,"h":297,"state":{},"id":3}],"edges":[{"source":[1,"beat"],"target":[2,"capture"]},{"source":[2,"jpg"],"target":[4,"jpg"]},{"source":[5,"image"],"target":[3,"image"]},{"source":[4,"jpg"],"target":[5,"dataurl"]}]},
    {"info":{"title":"doodle flipbook","author":"forresto","description":"paint doodle to image array to animated gif","url":"flipbook"},"nodes":[{"id":4,"src":"meemoo:variable/animation","x":875,"y":80,"w":389,"h":623,"state":{"fps":12,"pingpong":false}},{"id":5,"src":"meemoo:ui/button","x":138,"y":61,"w":360,"h":86,"state":{"label":"send and clear"}},{"id":7,"src":"meemoo:image/in","x":212,"y":283,"w":516,"h":520,"state":{}},{"id":3,"src":"meemoo:image/paint","x":213,"y":284,"w":511,"h":551,"state":{"width":500,"height":500,"fill":"red","stroke":"black","strokewidth":2,"tool":"smoothPencil","mode":"on","sendEvery":false}},{"id":6,"src":"meemoo:image/rectangle","x":145,"y":916,"w":167,"h":189,"state":{"x":0,"y":0,"w":500,"h":500,"stroke":"black","strokewidth":1}}],"edges":[{"source":[1,"image"],"target":[1,"tracing"]},{"source":[1,"image"],"target":[4,"push"]},{"source":[5,"bang"],"target":[1,"send"]},{"source":[5,"bang"],"target":[1,"clear"]},{"source":[6,"image"],"target":[3,"image"]},{"source":[3,"image"],"target":[4,"push"]},{"source":[5,"bang"],"target":[3,"send"]},{"source":[5,"bang"],"target":[3,"clear"]},{"source":[3,"image"],"target":[7,"image"]}]},
    {"info":{"title":"cam doodle","author":"forresto","description":"webcam to paint to animated gif... you can make a rotoscoping app by moving one wire","url":"camdoodle"},"nodes":[{"id":3,"src":"meemoo:image/cam","x":122,"y":191,"w":298,"h":384,"state":{"width":480,"height":480,"fps":20}},{"id":5,"src":"meemoo:variable/animation","x":727,"y":765,"w":347,"h":575,"state":{"fps":12,"pingpong":true}},{"id":2,"src":"meemoo:image/paint","x":707,"y":190,"w":507,"h":508,"state":{"width":480,"height":480,"fill":"red","stroke":"rgb(255, 255, 255)","strokewidth":2,"tool":"smoothPencil","mode":"on","sendEvery":false}},{"id":4,"src":"meemoo:ui/button","x":698,"y":52,"w":262,"h":70,"state":{"label":"Add frame"}},{"id":6,"src":"meemoo:ui/button","x":115,"y":52,"w":294,"h":81,"state":{"label":"Send image"}},{"id":7,"src":"meemoo:image/palette","x":148,"y":665,"w":287,"h":209,"state":{"max":16,"palette":["rgb(255,255,255)","rgb(128,128,128)","rgb(0,0,0)","rgb(255,0,0)","rgb(255,255,0)","rgb(0,255,0)","rgb(0,255,255)","rgb(0,0,255)","rgb(255,0,255)"]}}],"edges":[{"source":[3,"image"],"target":[1,"image"]},{"source":[1,"image"],"target":[5,"push"]},{"source":[3,"image"],"target":[2,"image"]},{"source":[2,"image"],"target":[5,"push"]},{"source":[4,"bang"],"target":[2,"send"]},{"source":[4,"bang"],"target":[2,"clear"]},{"source":[6,"bang"],"target":[3,"send"]},{"source":[3,"image"],"target":[7,"image"]},{"source":[7,"color"],"target":[2,"stroke"]}]},
    //{"info":{"title":"(speech to) text to speech","author":"forresto","description":"(in chrome, speech to) text to speech","url":"text2speech"},"nodes":[{"src":"https://forresto.github.io/meemoo-modules/speech2text.html","x":162,"y":61,"w":346,"h":98,"state":{},"id":1},{"src":"https://forresto.github.io/meemoo-speak.js/text2speech.html","x":234,"y":221,"w":167,"h":117,"state":{"amplitude":100,"pitch":50,"speed":175,"wordgap":0},"id":2},{"src":"https://forresto.github.io/meemoo-modules/audioarray.html","x":657,"y":227,"w":330,"h":280,"state":{},"id":3}],"edges":[{"source":[2,"info"],"target":[3,"title"]},{"source":[2,"audio"],"target":[3,"audio"]},{"source":[1,"text"],"target":[2,"text"]}]}
  ];

  Iframework.loadExampleApps(exampleApps);
});
